// @ts-check
/**
 * ESLint configuration for the whole monorepo.
 *
 * Type-aware linting is enabled deliberately. The rules it unlocks are the ones that
 * catch real faults in a financial API -- an un-awaited database write
 * (`no-floating-promises`), an async function passed where a sync one is expected
 * (`no-misused-promises`), a `Decimal` silently stringified into a template. Those are
 * exactly the bugs that would otherwise surface as a wrong balance.
 *
 * Formatting is Prettier's job; `eslint-config-prettier` must stay last so it can switch
 * off any stylistic rule that would conflict.
 */
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      // Generated by `prisma generate`; it ships its own eslint-disable header anyway.
      'backend/src/generated/**',
      '**/*.tsbuildinfo',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        // Resolves each file to its own tsconfig, which is what makes the monorepo's
        // three separate projects lint correctly.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      // --- correctness -------------------------------------------------------
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'off', // noisy with defensive checks
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-param-reassign': 'error',
      'prefer-const': 'error',
      'no-var': 'error',

      // --- typing discipline -------------------------------------------------
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Money is a Decimal-backed object; stringifying one implicitly would be a bug.
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: false, allowBoolean: false, allowNullish: false },
      ],
      '@typescript-eslint/explicit-function-return-type': [
        'warn',
        {
          allowExpressions: true,
          allowTypedFunctionExpressions: true,
          allowHigherOrderFunctions: true,
        },
      ],

      // --- style (non-conflicting with Prettier) -----------------------------
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
    },
  },

  // ---------------------------------------------------------------- backend
  {
    files: ['backend/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      // The API must never print to stdout outside the structured logger.
      'no-console': 'error',
    },
  },

  // --------------------------------------------------------------- frontend
  {
    files: ['frontend/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // Configured explicitly rather than through the plugins' preset exports, so an
      // upgrade cannot silently change which rules are active.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // `console.error` in the error boundary is intentional until Phase 14 wires an
      // error-tracking service.
      'no-console': ['error', { allow: ['error'] }],
    },
  },

  // ------------------------------------------------------------ shared types
  {
    files: ['shared/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
  },

  // ------------------------------------------------------------------ tests
  {
    files: ['**/tests/**/*.ts', '**/*.test.ts', '**/*.test.tsx'],
    rules: {
      // Supertest and fetch mocks hand back `any`; asserting on it is the whole point of
      // an HTTP contract test, so the unsafe-* family is relaxed here only.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
    },
  },

  // -------------------------------------------------------- config & tooling
  {
    files: ['**/*.config.ts', 'backend/prisma.config.ts', 'backend/prisma/seed.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      'no-console': 'off',
    },
  },

  // This file itself, and any other plain JS tooling, sits outside the TypeScript
  // projects, so type-aware rules cannot run on it.
  {
    files: ['**/*.{mjs,cjs,js}'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  prettier,
);
